-- Insert categories
INSERT INTO CATEGORIES (NAME) VALUES ('Electronics');
INSERT INTO CATEGORIES (NAME) VALUES ('Books');

-- Insert user
INSERT INTO USERS (EMAIL, IS_ACTIVE, PASSWORD, ROLE)
VALUES ('test@test.com', 1, '$2a$10$tU/RrCUPc4S9m7jyIFyrgeXooyofTmALkC7o/FyZPeRmOa0fqg/wK', 1);

-- Insert products
INSERT INTO PRODUCTS (DESCRIPTION, NAME, PRICE, CATEGORY_ID)
VALUES ('Smartphone with 5G', 'Phone X', 699.99, 1);

INSERT INTO PRODUCTS (DESCRIPTION, NAME, PRICE, CATEGORY_ID)
VALUES ('Science fiction novel', 'The Galaxy', 19.99, 2);

INSERT INTO PRODUCTS (DESCRIPTION, NAME, PRICE, CATEGORY_ID)
VALUES ('Noise-cancelling headphones', 'QuietBeats', 149.99, 1);

-- Insert favorites
INSERT INTO USER_FAVORITE_PRODUCTS (USER_ID, PRODUCT_ID)
VALUES (1, 1);

INSERT INTO USER_FAVORITE_PRODUCTS (USER_ID, PRODUCT_ID)
VALUES (1, 3);

INSERT INTO USER_FAVORITE_PRODUCTS (USER_ID, PRODUCT_ID)
VALUES (2, 2);
