-- Insert categories
INSERT INTO CATEGORIES (NAME) VALUES ('Electronics');
INSERT INTO CATEGORIES (NAME) VALUES ('Books');

-- Insert users
INSERT INTO USERS (EMAIL, IS_ACTIVE, PASSWORD, ROLE) VALUES ('user1@example.com', TRUE, 'password1', 1);
INSERT INTO USERS (EMAIL, IS_ACTIVE, PASSWORD, ROLE) VALUES ('user2@example.com', TRUE, 'password2', 2);
INSERT INTO USERS (EMAIL, IS_ACTIVE, PASSWORD, ROLE) VALUES ('test@test.com', TRUE, '$2a$10$qUL6x03J/bLjMfQAlB9AFeKGsvzO1AD3O215BiC8iJk.lCRq8YTWK', 1);

-- Insert products
INSERT INTO PRODUCTS (DESCRIPTION, NAME, PRICE, CATEGORY_ID) VALUES ('Smartphone with 5G', 'Phone X', 699.99, 1);
INSERT INTO PRODUCTS (DESCRIPTION, NAME, PRICE, CATEGORY_ID) VALUES ('Science fiction novel', 'The Galaxy', 19.99, 2);
INSERT INTO PRODUCTS (DESCRIPTION, NAME, PRICE, CATEGORY_ID) VALUES ('Noise-cancelling headphones', 'QuietBeats', 149.99, 1);

-- Insert favorites
INSERT INTO USER_FAVORITE_PRODUCTS (USER_ID, PRODUCT_ID) VALUES (1, 1);
INSERT INTO USER_FAVORITE_PRODUCTS (USER_ID, PRODUCT_ID) VALUES (1, 3);
INSERT INTO USER_FAVORITE_PRODUCTS (USER_ID, PRODUCT_ID) VALUES (2, 2);