CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE NUMERIC(3,0) NOT NULL
);

CREATE TABLE CATEGORIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    PRICE FLOAT,
    CATEGORY_ID BIGINT NOT NULL,
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

CREATE TABLE USER_FAVORITE_PRODUCTS (
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, PRODUCT_ID),
    CONSTRAINT FK_UFP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_UFP_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);